---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  roles:
    - role: geerlingguy.postgresql

  tasks:
    - name: Get odoo nightly key
      shell: |
        wget -qO- https://nightly.odoo.com/odoo.key | apt-key add -
        echo "deb http://nightly.odoo.com/12.0/nightly/deb/ ./" > /etc/apt/sources.list.d/odoo.list
    
    - name: Install Odoo
      apt:
        name: odoo
        state: latest
        update_cache: yes

    - name: Copy file with owner and permissions
      copy:
        src: "/vagrant/config/odoo.conf"
        dest: "/etc/odoo/odoo.conf"
        owner: "{{ odoo_user }}"
        group: "{{ odoo_group }}"
        mode: '0640'

    - debug: var=hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']