---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Update cache & upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Add odoo group
      group:
        name: "{{ odoo_user }}"
        state: present

    - name: Add odoo user and group
      user:
        name: "{{ odoo_user }}"
        group: "{{ odoo_group }}"
        home: "{{ odoo_dir }}"
        state: present

    - name: Install python dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
          - build-essential
          - wget
          - python3-dev
          - python3-venv
          - python3-wheel
          - libxslt-dev
          - libzip-dev
          - libldap2-dev
          - libsasl2-dev
          - python3-setuptools
          - node-less
          - libjpeg-dev
          - gdebi                    
        state: latest
    
    - name: Install python PIP dependencies
      apt:
        name:
          - libpq-dev
          - python-dev
          - libxml2-dev
          - libxslt1-dev
          - libldap2-dev
          - libsasl2-dev
          - libffi-dev
        state: latest
                    

    - name: Ensure npm are installed
      apt:
        name:
          - nodejs
          - npm
        state: latest

    - name: Install "less & plugins" node.js package globally.
      shell: npm install -g less less-plugin-clean-css rtlcss
        
    - name: Ensure node-less & xfonts is installed
      apt:
        name:
          - node-less
          - xfonts-75dpi
          - xfonts-base
        state: latest

    - name: Install wkhtmltopdf
      shell: |
        cd "{{ home_dir }}"
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        apt install ./wkhtmltox_0.12.5-1.bionic_amd64.deb
      args:
        creates: /usr/local/bin/wkhtmltopdf
        